version: '3'
services:
  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - db
    environment:
      - DEFAULT_USER=${PG_ADMIN_DEFAULT_USER}
      - DEFAULT_PASSWORD=${PG_ADMIN_DEFAULT_PASSWORD}
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=https://${DOMAIN}/api/v1/swagger/
  proxy:
    image: traefik:v1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: totem/celery-flower-docker
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
