"""Vehicle and Accusation models

Revision ID: 1a4d5b275005
Revises: a404eea364dc
Create Date: 2018-11-04 02:28:50.183364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4d5b275005'
down_revision = 'a404eea364dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accusation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=160), nullable=True),
    sa.Column('occured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('accusationtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index(op.f('ix_vehicle_created_at'), 'vehicle', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_created_at'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('accusationtype')
    op.drop_table('accusation')
    # ### end Alembic commands ###
