"""Add AccusationType model

Revision ID: 1d1d2f1e23b7
Revises: 1a4d5b275005
Create Date: 2018-11-12 10:32:24.866588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1d2f1e23b7'
down_revision = '1a4d5b275005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accusation', sa.Column('acc_type_id', sa.Integer(), nullable=False))
    op.add_column('accusation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('accusation', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accusation', 'accusationtype', ['acc_type_id'], ['id'])
    op.create_foreign_key(None, 'accusation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'accusation', 'vehicle', ['vehicle_id'], ['id'])
    op.drop_index('ix_vehicle_id', table_name='vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vehicle_id', 'vehicle', ['id'], unique=False)
    op.drop_constraint(None, 'accusation', type_='foreignkey')
    op.drop_constraint(None, 'accusation', type_='foreignkey')
    op.drop_constraint(None, 'accusation', type_='foreignkey')
    op.drop_column('accusation', 'vehicle_id')
    op.drop_column('accusation', 'user_id')
    op.drop_column('accusation', 'acc_type_id')
    # ### end Alembic commands ###
