"""Add slug column to accusationtype

Revision ID: beeb6e57444d
Revises: 1d1d2f1e23b7
Create Date: 2018-11-14 10:28:15.591523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beeb6e57444d'
down_revision = '1d1d2f1e23b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accusationtype', sa.Column('slug', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_accusationtype_desc'), 'accusationtype', ['desc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accusationtype_desc'), table_name='accusationtype')
    op.drop_column('accusationtype', 'slug')
    # ### end Alembic commands ###
